import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you want
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {/* Uncomment this line if you want to include the Header */}
        {/* <Header /> */}
        <main>{children}</main>
      </body>
    </html>
  );
}
